apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/Surajjadhav97/Ruby-Application-ArgoCD
    path: kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

