apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-application
  template:
    metadata:
      labels:
        app: rails-application
    spec:
      containers:
        - name: rails-application
          image: ruby:3.1.4-slim-bullseye
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails-application
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

